logging:
  config: classpath:logback-winner.xml
  
server:
  port: 8080
  session-timeout: 60

connection: 
    resources: /res
    redsWorkSize: 7
    serID: 1
    zkHosts: 192.168.56.2:2181
    applicationPath: 

management:
    health:
        redis:
            enabled: true
            order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP

jasypt:
    encryptor:
        password: e!Jd&ljyJ^e4I5oU
    
spring:
    datasource:
        db01:
           url: jdbc:mysql://192.168.56.2:3306/classDB?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
           username: classuser
           password: ENC(xfcqz2HNCeY=)
           driverClassName: com.mysql.jdbc.Driver
           minPoolSize: 3
           maxPoolSize: 25
           maxLifetime: 20000
           maxWaitTime: 60000
           borrowConnectionTimeout: 30
           loginTimeout: 30
           maintenanceInterval: 60
           test.maxIdleTime: 60
           testQuery: select 1
           mapperLocations: classpath:/com/liu/springboot/quickstart/mapper/db01mapper/*.xml
           baseMapperLocations: classpath:/com/liu/springboot/quickstart/mapper/basemapper/*.xml
           configLocation: classpath:/mybatis-config.xml
        db02:
           url: jdbc:mysql://192.168.56.2:3306/classDB2?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
           username: classuser
           password: 123456
           driverClassName: com.mysql.jdbc.Driver
           minPoolSize: 3
           maxPoolSize: 25
           maxLifetime: 20000
           maxWaitTime: 60000
           borrowConnectionTimeout: 30
           loginTimeout: 30
           maintenanceInterval: 60
           test.maxIdleTime: 60
           testQuery: select 1
           mapperLocations: classpath:/com/liu/springboot/quickstart/mapper/db02mapper/*.xml
           baseMapperLocations: classpath:/com/liu/springboot/quickstart/mapper/basemapper/*.xml
           configLocation: classpath:/mybatis-config.xml
    redis:
        cn:
           database: 0
           host: 192.168.56.2
           port: 6379
           password: 123456
           timeout: 60
           maxTotal: 10
           maxWait: 6000
           maxIdle: 8
           minIdle: 3
    resources:
        static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/webapp/
        chain:
            strategy:
                content:
                    enabled: true
                    paths: /**
    thymeleaf:
        prefix: classpath:/tem/
        suffix: .html
        mode: HTML5
        encoding: UTF-8
        cache: false
    task:
        corePoolSize: 10
        maxPoolSize: 15
        queueCapacity: 3
        keepAliveSeconds: 200
        threadNamePrefix: taskExecutor_