logging:
  config: classpath:logback.xml
  path: d:/logs
server:
  port: 8080
  session-timeout: 60

connection: 
    resources: /res

spring:
    datasource:
        db01:
           url: jdbc:mysql://192.168.56.2:3306/classDB?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
           username: classuser
           password: 123456
           driverClassName: com.mysql.jdbc.Driver
           minPoolSize: 3
           maxPoolSize: 25
           maxLifetime: 20000
           maxWaitTime: 60000
           borrowConnectionTimeout: 30
           loginTimeout: 30
           maintenanceInterval: 60
           test.maxIdleTime: 60
           testQuery: select 1
           mapperLocations: classpath:/com/liu/springboot/quickstart/mapper/db01mapper/*.xml
           baseMapperLocations: classpath:/com/liu/springboot/quickstart/mapper/basemapper/*.xml
           configLocation: classpath:/mybatis-config.xml
        db02:
           url: jdbc:mysql://192.168.56.2:3306/classDB2?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
           username: classuser
           password: 123456
           driverClassName: com.mysql.jdbc.Driver
           minPoolSize: 3
           maxPoolSize: 25
           maxLifetime: 20000
           maxWaitTime: 60000
           borrowConnectionTimeout: 30
           loginTimeout: 30
           maintenanceInterval: 60
           test.maxIdleTime: 60
           testQuery: select 1
           mapperLocations: classpath:/com/liu/springboot/quickstart/mapper/db02mapper/*.xml
           baseMapperLocations: classpath:/com/liu/springboot/quickstart/mapper/basemapper/*.xml
           configLocation: classpath:/mybatis-config.xml
    redis:
        database: 0
        host: 192.168.56.2
        port: 6379  
        password: 123456
        maxActive: 10
        maxWaitTime: 60000
        maxIdle: 60
        minIdle: 0
        timeout: 60
    resources:
        static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,classpath:/webapp/
        chain:
            strategy:
                content:
                    enabled: true
                    paths: /**
    thymeleaf:
        prefix: classpath:/tem/
        suffix: .html
        mode: HTML5
        encoding: UTF-8